SQUAT = 'squat'
HALTERE_GAUCHE = 'soulèvement d\'haltère du bras gauche'
HALTERE_DROIT = 'soulèvement d\'haltère du bras droit'
FENTE_DROIT = 'fente pied droit avant'
FENTE_GAUCHE = 'fente pied gauche avant'
PAUSE = 'pause'